apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
data:
  DB_HOST: "sample-db"
  DB_PORT: "5432"
  DB_NAME: {{ .Values.db.name | quote }}
  DB_USER: {{ .Values.db.user | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sample-secret
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.db.password | quote }}
